### ISSUE TITLE
Cannot have @ symbol in RPC passwords

### ISSUE THREAD

**Issue by radixrat** [lightningdevkit/ldk-sample#38]
I tried to use this tool and was unable to connect, after digging I found out it was because of the split procedure and the expectation of 2 vectors after split. I opened a PR with a potential fix, which allowed me to get through this block, I am still new to rust.

https://github.com/lightningdevkit/ldk-sample/pull/37

**Comment by TheBlueMatt** [comment]
Fixed in #37.
