### ISSUE TITLE
Catch ^C

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningdevkit/ldk-sample#76]
And tell users to use ^D.

**Comment by tnull** [comment]
Seems this is not as straightforward as one might think, at least if we want to make it work on all platforms. IIUC `std` does not support signal handling sufficiently, so we either handle this via unsafe `libc` code and try to catch all platform-dependent quirks, or just take a dependency on the `ctrlc` crate. Are we fine doing the latter?
